# Generated by Django 4.2.16 on 2024-11-16 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LifestylePreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MinLengthOfStayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeOfStayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(error_messages={'unique': 'This phone number already exists in our database'}, max_length=15, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('gender', models.CharField(max_length=10)),
                ('passport', models.FileField(default='/Users/apple/Downloads/relax_housing/passport_default_file.jpeg', help_text='Passport file as identity proof', upload_to='passports/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(related_name='users', to='users.interestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocationDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField(blank=True, default=0)),
                ('city_id', models.IntegerField(blank=True, default=0)),
                ('city_name', models.CharField(default='', max_length=200)),
                ('country_id', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccommodationInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None)),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.additionalpreferencemodel')),
                ('city_accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_city', to='location.citiesmodel')),
                ('city_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='location.citiesmodel')),
                ('lifestyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lifestylepreferencemodel')),
                ('min_length_of_stay', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='min_stay', to='users.minlengthofstaymodel')),
                ('purpose_of_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_of_stay', to='users.purposeofstaymodel')),
                ('room_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roompreferencemodel')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
